"""update to segment list

Revision ID: 72beb66af629
Revises: 14001b5a1cab
Create Date: 2023-10-01 07:57:26.710019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72beb66af629'
down_revision = '14001b5a1cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.Integer(), nullable=False))
        batch_op.drop_column('segemnt_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segemnt_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('segment_id')

    # ### end Alembic commands ###
