"""added approval field to segment_list

Revision ID: 73247b8fe548
Revises: 72beb66af629
Create Date: 2023-10-13 19:40:31.654925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73247b8fe548'
down_revision = '72beb66af629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_list', schema=None) as batch_op:
        batch_op.drop_column('approval')

    # ### end Alembic commands ###
