"""Initial migration.

Revision ID: a95de06edf90
Revises: 
Create Date: 2023-09-23 22:25:31.585948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95de06edf90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('profile_pic_medium', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Integer(), nullable=True),
    sa.Column('prefer_units', sa.Enum('Imperial', 'Metric', name='unit_measurement'), nullable=False),
    sa.Column('strava_access_token', sa.String(), nullable=True),
    sa.Column('strava_refresh_token', sa.String(), nullable=True),
    sa.Column('strava_token_type', sa.String(), nullable=True),
    sa.Column('strava_token_expires', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('strava_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
